In [2]:
import numpy as np
import pandas as pd

Loading the data

In [5]:
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Core_Concept\\anime.csv")

In [6]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [8]:
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [ ]:
# function to extract the episodes from the title
def extract_episodes(txt):
    data = ""
    check = False
    for i in txt:
        if i == ")":
            break
        if i == "(":
            check = True
            continue
        if check == True:
            data += i
    return data

In [ ]:
# Making a new coloumn for episodes count
df["Episodes"] = df["Title"].apply(extract_episodes)

In [24]:
df["Episodes"] = df["Episodes"].str.replace(" eps","")

In [26]:
df.head()

,Rank,Title,Score,Episodes,episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,10

In [28]:
df["Episodes"] = df["Episodes"].astype(int)

In [31]:
df.head()

,Rank,Title,Score,Episodes,episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,10

In [33]:
df.loc[1]["Title"]

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [45]:
# Function to extract the time stamp from the title 
def extract_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i+1,i+20):
                data += txt[j]
            return data

In [47]:
# Making new coloumn for time stamp
df["Total Time"] = df["Title"].apply(extract_time)

In [48]:
df.head()

,Rank,Title,Score,Episodes,episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,10,Apr 2019 - Jul 2019

In [49]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total Time'].apply(calculate_total_months)

In [51]:
df.head()

,Rank,Title,Score,Episodes,episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,10,Apr 2019 - Jul 2019,4

In [53]:
# which anime has the highest score
df[df["Score"] == df["Score"].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [55]:
# Top 5 highest score anime
df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [56]:
# which anime has the highest episode count
df[df["Episodes"] == df["Episodes"].max()]["Title"]

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: str

In [ ]:
# Anime with top 5 episode count
df.sort_values(by= "Episodes",ascending=False)

In [ ]:
# longest running anime