## Pandas Series

A Series is a 1-dimensional labeled array capable of holding any data type. The axis labels are collectively called index.

### Creating Series

There are multiple ways to create a pandas Series:

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr,index = labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64